### PR TITLE
Add LAVA test definition

### PR DESCRIPTION
**Pull request by chase-qi**
Signed-off-by: Chase Qi <chase.qi@linaro.org>

### CODE REVIEW

**Comment by chase-qi** [comment]
Here is a LAVA job example https://validation.linaro.org/scheduler/job/1911037

@mwasilew Would you please also take a look?

**Comment by ndechesne** [comment]
hey,

can you explain a bit more why you want that here? In general LAVA test def are not in the upstream repo, but in test-definitions. Has anything changed or being discussed? 

anyways, thanks for writing it.. we've been using bootrr in LAVA using some poor's man script so far, see:
https://git.linaro.org/ci/job/configs.git/tree/lt-qcom-linux-test/lava-job-definitions/boards/template-bootrr.yaml#n184

**Comment by chase-qi** [comment]
Hi @ndechesne Thanks for the comments. I started with adding a yaml file to test-definitions with the following run steps.

```
params:
    # Refer to ./boards for boards supported.
    BOARD: "arrow,apq8096-db820c"
    SKIP_INSTALL: false

run:
    steps:
        - . ./automated/lib/sh-test-lib
        - install_deps git "${SKIP_INSTALL}"
        - git clone https://github.com/andersson/bootrr
        - export PATH=$PWD/helpers:$PATH
        - ./boards/${BOARD}
```
Milosz and I had a look, we figured that the bootrr project is pretty much self-contained, we don't need any utils or libraries from test-definitions to run it in LAVA, and we figured that if we put the yaml file in this repo, then we don't need to install git and do git clone as that will be done by lava-dispatcher. Less depends, more reliable, right? We thought that is the right way to go.

If you guys want to host the file in test-definitions, I am happy with that too. Please let me know.

**Comment by ndechesne** [comment]
I am not the maintainer here ;-) but I am not much in favor of adding the LAVA yaml file here.. just seems odd to me that we are making an exception here...

**Comment by chase-qi** [comment]
Thanks, Nico. @andersson, @mwasilew ^ comments?

**Comment by chase-qi** [comment]
Maybe, we do both? lava.yaml here and add test-definitions/automated/linux/bootrr/bootrr.yaml too?

**Comment by mwasilew** [comment]
I think there are 3 options to run these tests in LAVA:
1. this PR - adding yaml file to this repository
2. copying/moving scripts to test-definitions and maintaining them there with yaml file (at least the common part)
3. creating yaml file in test-defitnions and clone this repository during runtime 
4. rely on built in version (Nico's example)

IMHO option 3 is the worst one and it adds dependencies on git and networking in the DUT. 1 or 2 are equal from my pov but I would like to avoid hosting scripts in both repositories. I also have no problem adding more co-maintainers to test-definitions. Option 4 is controversial and I'm not in favour of having such test definitions at all.

**Comment by ndechesne** [comment]
> I think there are 3 options to run these tests in LAVA:
> 
> 1. this PR - adding yaml file to this repository

as I said, this looks wrong..

> 2. copying/moving scripts to test-definitions and maintaining them there with yaml file (at least the common part)

No definitely.. bootrr is useful for us outside of LAVA, and it shouldn't be maintained in test-definitions. 

> 3. creating yaml file in test-defitnions and clone this repository during runtime
> 4. rely on built in version (Nico's example)
> 
> IMHO option 3 is the worst one and it adds dependencies on git and networking in the DUT. 1 or 2 are equal from my pov but I would like to avoid hosting scripts in both repositories. I also have no problem adding more co-maintainers to test-definitions. Option 4 is controversial and I'm not in favour of having such test definitions at all.

I don't get it... especially your comment on #3, we run these tests on devices with "no" networking, all the test cases are added in the lava-overlay before the image is flashed on the DUT. To me #3 is the right solution. I agree that #4 is not too good.. since it's duplicated in every job.

**Comment by mwasilew** [comment]
To add tests to overlay you need some yaml to be executed on dispatched. It's either the yaml in this PR or the inline one in the lava test job. So what you're doing is basically option 1.

**Comment by ndechesne** [comment]
I see... our assumption for bootrr is that these scripts are added in the image. 

Bootrr is executed against an initramfs not a full image. So we build our initramfs and we build a cpio image for bootrr and we overlay the bootrr cpio in the boot image that we send to lava. 

I think this was the reason of our misunderstanding.. so let’s step back, and let me ask why are you submitting this PR in the first? How will you be using bootrr?

**Comment by chase-qi** [comment]
@ndechesne I sent the PR to put the test definition in this repo to avoid dependency installation and git clone on the target, that is the only reason. I agree that it is also adding an exception for test-definitions users. I am adding it to test-definitions https://github.com/Linaro/test-definitions/pull/53. 

bootrr maintainers, feel free to merge/close this PR please.

**Comment by alimon** [comment]
@chase-qi I prefer to have all the test definitions into [1] instead of spread into every upstream project. One improvement to [2] will be able to avoid using git to get bootrr by set a BOOTRR_DIR, we are pre-populating bootrr into a initramfs, I will send a PR.

[1] https://github.com/Linaro/test-definitions
[2] https://github.com/Linaro/test-definitions/pull/53/commits

**Comment by chase-qi** [comment]
> @chase-qi I prefer to have all the test definitions into [1] instead of spread into every upstream project. One improvement to [2] will be able to avoid using git to get bootrr by set a BOOTRR_DIR, we are pre-populating bootrr into a initramfs, I will send a PR.

Hi @alimon, I have merged the PR #53. Adding BOOTRR_DIR sounds good to me. Please send another PR to add the feature and add yourself to maintainer list. 

I am also closing this PR to avoid more confusions. 

Thanks,
Chase

> 
> [1] https://github.com/Linaro/test-definitions
> [2] https://github.com/Linaro/test-definitions/pull/53/commits

**Pull request closed without merging**
